name: Deploy to Render

on:
  push:
    branches: [main] # Set this to the branch you want to deploy from
  pull_request:
    branches: [main] # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Set this to the version of Python you're using

    - name: deploy
      env:
          DATABASE_CREDENTIALS: ${{ secrets.DATABASE_CREDENTIALS }}
          XCAPTCHA_SECRET_KEY: ${{ secrets.XCAPTCHA_SECRET_KEY }}
          XCAPTCHA_SITE_KEY: ${{ secrets.XCAPTCHA_SITE_KEY }}
      run: |
        pip install -r requirements.txt
    - name: show secret
      run: | 
        echo ${{ secrets.DATABASE_CREDENTIALS }}
        echo ${{ secrets.XCAPTCHA_SECRET_KEY }}
        echo ${{ secrets.XCAPTCHA_SITE_KEY }}